services:
  app:
    image: todo-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ./:/usr/src/app
    ports:
      - 8080:8080
    container_name: todo-frontend-dev